### PR TITLE
fix: useLayoutEffect only works on client side

### LINKED ISSUE #6: useLayoutEffect does nothing on the server
During SSR have this warning:
```Warning: useLayoutEffect does nothing on the server, because its effect cannot be encoded into the server renderer's output format. This will lead to a mismatch between the initial, non-hydrated UI and the intended UI. To avoid this, useLayoutEffect should only be used in components that render exclusively on the client. See https://reactjs.org/link/uselayouteffect-ssr for common fixes.```

The code producing it:
https://github.com/react-component/overflow/blob/58885d10ee46791f48373504e8313e726b40920b/src/Overflow.tsx#L151

### PR DESCRIPTION
**Pull request by dimbslmh**
Fixes #6

### CODE REVIEW

**Comment by zombieJ** [comment]
Seems it should move to `rc-util` since too many place need this.

**Comment by dimbslmh** [comment]
> Seems it should move to `rc-util` since too many place need this.

@zombieJ yeah. there seems to be a PR already covering this case done by @yoyo837 https://github.com/react-component/util/pull/252

**Comment by dimbslmh** [comment]
@zombieJ please check out this search: https://github.com/search?q=org%3Areact-component+useLayoutEffect&type=code.

As you said, multiple packages are using the React.useLayoutEffect hook.
There are different approaches in other packages:
react-component/select has its own isBrowserClient in '../utils/commonUtil';
react-component/motion and react-component/input-number are using canUseDom from 'rc-util/lib/Dom/canUseDom';

What would you like to do?

**Comment by zombieJ** [comment]
Since this warning is useless, pick strict one is enough for test env?

**Comment by dimbslmh** [comment]
If you want to be able to test useLayoutEffect in the test environment you could use this: 
https://www.npmjs.com/package/jest-react-hooks-shallow

**Comment by kiyasov** [comment]
> Since this warning is useless, pick strict one is enough for test env?

Hi! When will the fix be released?

**Comment by zombieJ** [comment]
https://github.com/react-component/util/pull/252  merged. Can move to rc-util instead

**Pull request closed without merging**
